AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::061051230398:role/gl-lambda-execution-role'
      Environment:
        Variables:
          TARGET_BUCKET: gl-rootdevelopper-inter-store
      Layers:
        - 'arn:aws:lambda:us-east-1:061051230398:layer:tika:1'
